// This illustrates that a groovy task can initiate a failure by
// throwing exceptions
def a = 1
def b = 0
def c = a / b